//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pobie.Roslyn {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pobie.Roslyn.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FluentAssertions should always include a &quot;because&quot; argument to clarify the intent..
        /// </summary>
        internal static string UT0001Description {
            get {
                return ResourceManager.GetString("UT0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertions should include a &quot;because&quot; argument explaining the reason..
        /// </summary>
        internal static string UT0001MessageFormat {
            get {
                return ResourceManager.GetString("UT0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &quot;because&quot; argument in assertion.
        /// </summary>
        internal static string UT0001Title {
            get {
                return ResourceManager.GetString("UT0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure &quot;because&quot; values start with &quot;because&quot; to improve clarity..
        /// </summary>
        internal static string UT0002Description {
            get {
                return ResourceManager.GetString("UT0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;because&quot; value should begin with the word &quot;because&quot;..
        /// </summary>
        internal static string UT0002MessageFormat {
            get {
                return ResourceManager.GetString("UT0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;because&quot; value should start with &quot;because&quot;.
        /// </summary>
        internal static string UT0002Title {
            get {
                return ResourceManager.GetString("UT0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t end &quot;because&quot; values with a period for better readability..
        /// </summary>
        internal static string UT0003Description {
            get {
                return ResourceManager.GetString("UT0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;because&quot; value should not end with punctuation..
        /// </summary>
        internal static string UT0003MessageFormat {
            get {
                return ResourceManager.GetString("UT0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;because&quot; value should not end with punctuation.
        /// </summary>
        internal static string UT0003Title {
            get {
                return ResourceManager.GetString("UT0003Title", resourceCulture);
            }
        }
    }
}
