name: Build and Publish Analyzers to NuGet

on:
  push:
    branches:
      - main

jobs:
  tag_on_main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.2.x'

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.2.0
        with:
          updateProjectFiles: 'true'
          
      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.version_step.outputs.FullSemVer }}
          git push origin ${{ steps.version_step.outputs.FullSemVer }}