name: Build

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' 

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Run Analyzers.Tests
        run: dotnet test ./Pobie.Roslyn.Analyzers.Tests/Pobie.Roslyn.Analyzers.Tests.csproj --configuration Release

      - name: Build Analyzers project
        run: dotnet build ./Pobie.Roslyn.Analyzers/Pobie.Roslyn.Analyzers.csproj --configuration Release
